/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

LeetCode: 389. Find the Difference
*/

var findTheDifference = function(s, t) {
    for(let i = 0; i < s.length; i++) {
        t = t.replace(s[i], "");
    }
    return t
};