/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

LeetCode: 389. Find the Difference
*/

var findTheDifference = function(s, t) {
    let seen = {};
    let seen2 = {};
    for(let el of s){
        seen[el] = (seen[el] || 0) + 1
    }
    for(let el of t){
        seen2[el] = (seen2[el] || 0) + 1
    }
    for(let el of t){
        if(seen2[el] - seen[el] !== 0) return el;
    }
};
findTheDifference("a", "aa")